spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fileuploads
    username: postgres
    password: setha
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

#    file upload properties
  file:
    server_path: "C:\\Users\\User\\Desktop\\server\\"
    base_url: "http://localhost:8080/api/v1/files/"
    base_download_url: "http://localhost:8080/api/v1/files/download/"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


